'''Chooses a random number between two integers chosen by user, and lets the user guess the number. Will tell the user if the number they guessed is too high or low.'''
import random

def main():

    numgen()
    guesser()


def numgen():
    '''Generates a random number between two user specified integers.'''
    while True:
        while True:
            try:
                numgen.lower = int(float(input("Enter lower limit for number generated: ")))
            except ValueError:
                print("Please enter a number.")
                continue
            else:
                break
        while True:
            try:
                numgen.upper = int(float(input("Enter upper limit for number generated: ")))
            except ValueError:
                print("Please enter a number.")
                continue
            else:
                break
        if numgen.upper < numgen.lower:
            print("Please ensure the upper limit is higher than the lower limit.")
            continue
        else: 
            break

    numgen.number = random.randint(numgem.lower, numgem.upper)
    print("numgen.number:   ", numgen.number)

def guesser():
    '''Compares the user's guess and indicates whether it is lower, higher, or equal to the number generated by numgen func. If equal to, ends the program.'''
    usrinput = "marker"
    while True:
        while usrinput == "marker":
            try:
                usrinput = int(float(input("Guess a number between {:d} and {:d}: ".format(numgen.lower, numgen.upper))))
            except ValueError:
                print("Please enter a number.")
                continue
            else:
                break
    
        while usrinput > numgen.number:
            try:
                usrinput = int(float(input("{:d} is too high. Guess again： ".format(usrinput))))
                continue 
            except ValueError:
                print("Please enter a number.")
                continue
            else:
                break

        while usrinput < numgen.number:
            try:
                usrinput = int(float(input("{:d} is too low. Guess again： ".format(usrinput))))
                continue 
            except ValueError:
                print("Please enter a number.")
                continue
            else:
                break

        if usrinput == numgen.number:
            print("The correct answer was {:d}! You win!!!".format(numgen.number))
            break


main()